CREATE TABLE IF NOT EXISTS USERS
(
    user_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(200)                         NOT NULL,
    email     VARCHAR(200)                         NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS LOCATIONS
(
    location_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat         FLOAT                                NOT NULL,
    lon         FLOAT                                NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    category_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(200)                         NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    event_id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(200)                         NOT NULL,
    created_on         TIMESTAMP                            NOT NULL,
    description        VARCHAR(200)                         NOT NULL,
    event_date         TIMESTAMP                            NOT NULL,
    initiator_id       INT                                  NOT NULL REFERENCES USERS (user_id) ON DELETE CASCADE,
    location_id        INT                                  NOT NULL REFERENCES LOCATIONS (location_id) ON DELETE CASCADE,
    paid               BOOLEAN                              NOT NULL,
    participant_limit  INT                                  NOT NULL,
    published_on       TIMESTAMP                            NOT NULL,
    request_moderation BOOLEAN                              NOT NULL,
    state              VARCHAR(200)                         NOT NULL,
    title              VARCHAR(200)                         NOT NULL,
    views              INT                                  NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS EVENT_CATEGORIES
(
    category_id INT NOT NULL REFERENCES CATEGORIES (category_id) ON DELETE CASCADE,
    event_id    INT NOT NULL REFERENCES EVENTS (event_id) ON DELETE CASCADE,
    CONSTRAINT pk_event_categories PRIMARY KEY (category_id, event_id)
);

CREATE TABLE IF NOT EXISTS EVENT_JOIN_REQUESTS
(
    request_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP                            NOT NULL,
    event_id     INT                                  NOT NULL REFERENCES EVENTS (event_id) ON DELETE CASCADE,
    requester_id INT                                  NOT NULL REFERENCES USERS (user_id) ON DELETE CASCADE,
    status       VARCHAR(200)                         NOT NULL,
    CONSTRAINT pk_event_join_requests PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS COMPILATIONS
(
    compilation_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned         BOOLEAN                              NOT NULL,
    title          VARCHAR(200)                         NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS EVENTS_COMPILATIONS
(
    compilation_id INT NOT NULL REFERENCES COMPILATIONS (compilation_id) ON DELETE CASCADE,
    event_id       INT NOT NULL REFERENCES EVENTS (event_id) ON DELETE CASCADE,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, event_id)
);