CREATE TABLE IF NOT EXISTS HIT_STATS
(
    hit_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app             VARCHAR(200)                         NOT NULL,
    uri             VARCHAR(200)                         NOT NULL,
    ip              VARCHAR(200)                         NOT NULL,
    hit_time        TIMESTAMP                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (hit_id)
);