CREATE TABLE IF NOT EXISTS HITS
(
    hit_id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hit_app    VARCHAR(200)                         NOT NULL,
    hit_text   VARCHAR(200)                         NOT NULL,
    hit_amount INT                                  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (hit_id)
);